package io.quarkus.bean.validation.impl;

import java.lang.annotation.Annotation;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;

/**
 * Base class for build-time generated constraint annotation literal classes.
 * <p>
 * Stores the annotation type and a map of coerced attribute values. Subclasses
 * (generated by Gizmo) implement the annotation interface and delegate to the
 * typed getter methods provided here.
 *
 * @param <A> the annotation type
 */
public abstract class AbstractConstraintAnnotationLiteral<A extends Annotation> implements Annotation {

    private final Class<A> annotationType;
    private final Map<String, Object> attributes;

    protected AbstractConstraintAnnotationLiteral(Class<A> annotationType, Map<String, Object> rawAttributes) {
        this.annotationType = annotationType;
        this.attributes = coerceAll(annotationType, rawAttributes);
    }

    /**
     * Iterates over the annotation type's declared methods to coerce each raw attribute
     * value to the correct type. Falls back to {@link Method#getDefaultValue()} for
     * missing attributes.
     */
    private static <A extends Annotation> Map<String, Object> coerceAll(Class<A> annotationType,
            Map<String, Object> rawAttributes) {
        Map<String, Object> coerced = new HashMap<>();
        for (Method method : annotationType.getDeclaredMethods()) {
            if (method.getParameterCount() != 0) {
                continue;
            }
            String name = method.getName();
            Object raw = rawAttributes != null ? rawAttributes.get(name) : null;
            if (raw != null) {
                coerced.put(name, AnnotationUtils.coerceValue(raw, method.getReturnType()));
            } else {
                Object defaultValue = method.getDefaultValue();
                if (defaultValue != null) {
                    coerced.put(name, defaultValue);
                }
            }
        }
        // Keep any extra entries that don't correspond to annotation methods
        // (e.g., pre-resolved groups/payload as Class[] arrays)
        if (rawAttributes != null) {
            for (Map.Entry<String, Object> entry : rawAttributes.entrySet()) {
                if (!coerced.containsKey(entry.getKey())) {
                    coerced.put(entry.getKey(), entry.getValue());
                }
            }
        }
        return coerced;
    }

    // ---- Typed attribute getters for generated subclasses ----

    protected String getStringAttr(String name) {
        return (String) attributes.get(name);
    }

    protected int getIntAttr(String name) {
        Object v = attributes.get(name);
        return v instanceof Number ? ((Number) v).intValue() : 0;
    }

    protected long getLongAttr(String name) {
        Object v = attributes.get(name);
        return v instanceof Number ? ((Number) v).longValue() : 0L;
    }

    protected boolean getBooleanAttr(String name) {
        Object v = attributes.get(name);
        return v instanceof Boolean && (Boolean) v;
    }

    protected double getDoubleAttr(String name) {
        Object v = attributes.get(name);
        return v instanceof Number ? ((Number) v).doubleValue() : 0.0;
    }

    protected float getFloatAttr(String name) {
        Object v = attributes.get(name);
        return v instanceof Number ? ((Number) v).floatValue() : 0.0f;
    }

    protected short getShortAttr(String name) {
        Object v = attributes.get(name);
        return v instanceof Number ? ((Number) v).shortValue() : (short) 0;
    }

    protected byte getByteAttr(String name) {
        Object v = attributes.get(name);
        return v instanceof Number ? ((Number) v).byteValue() : (byte) 0;
    }

    protected char getCharAttr(String name) {
        Object v = attributes.get(name);
        return v instanceof Character ? (Character) v : '\0';
    }

    @SuppressWarnings("unchecked")
    protected <T> Class<T> getClassAttr(String name) {
        return (Class<T>) attributes.get(name);
    }

    protected Class<?>[] getClassArrayAttr(String name) {
        return (Class<?>[]) attributes.get(name);
    }

    @SuppressWarnings("unchecked")
    protected <E extends Enum<E>> E getEnumAttr(String name, Class<E> enumType) {
        return (E) attributes.get(name);
    }

    @SuppressWarnings("unchecked")
    protected <E extends Enum<E>> E[] getEnumArrayAttr(String name, Class<E> enumType) {
        return (E[]) attributes.get(name);
    }

    protected String[] getStringArrayAttr(String name) {
        return (String[]) attributes.get(name);
    }

    protected int[] getIntArrayAttr(String name) {
        return (int[]) attributes.get(name);
    }

    protected long[] getLongArrayAttr(String name) {
        return (long[]) attributes.get(name);
    }

    @SuppressWarnings("unchecked")
    protected <T> T getObjectAttr(String name) {
        return (T) attributes.get(name);
    }

    // ---- Annotation contract ----

    @Override
    public Class<? extends Annotation> annotationType() {
        return annotationType;
    }

    @Override
    public int hashCode() {
        int result = 0;
        for (Method method : annotationType.getDeclaredMethods()) {
            if (method.getParameterCount() != 0) {
                continue;
            }
            String name = method.getName();
            Object value = attributes.get(name);
            int nameHash = name.hashCode() * 127;
            int valueHash = AnnotationUtils.memberHashCode(value);
            result += nameHash ^ valueHash;
        }
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!annotationType.isInstance(other)) {
            return false;
        }
        for (Method method : annotationType.getDeclaredMethods()) {
            if (method.getParameterCount() != 0) {
                continue;
            }
            try {
                Object thisValue = attributes.get(method.getName());
                Object otherValue = method.invoke(other);
                if (!AnnotationUtils.memberEquals(thisValue, otherValue)) {
                    return false;
                }
            } catch (ReflectiveOperationException e) {
                return false;
            }
        }
        return true;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append('@').append(annotationType.getName()).append('(');
        Method[] methods = annotationType.getDeclaredMethods();
        boolean first = true;
        for (Method method : methods) {
            if (method.getParameterCount() != 0) {
                continue;
            }
            if (!first) {
                sb.append(", ");
            }
            sb.append(method.getName()).append('=');
            Object v = attributes.get(method.getName());
            if (v != null && v.getClass().isArray()) {
                sb.append(AnnotationUtils.arrayToString(v));
            } else {
                sb.append(v);
            }
            first = false;
        }
        sb.append(')');
        return sb.toString();
    }
}
